/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject3;

import java.sql.SQLException;

/**
 *
 * @author xavia
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Resultat = new javax.swing.JLabel();
        terra = new javax.swing.JTextField();
        nomPlaneta = new javax.swing.JTextField();
        fotoPlanetaDestino = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular distancia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(59, 89, 200));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jList1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mart", "Venus", "Ura", "Saturn", "Mercuri", "Neptu" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 160));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 20)); // NOI18N
        jTextField1.setText("Anys que es tardara en arribar:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 390, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\tierra.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 100, 100));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Destí");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        Resultat.setText("jLabel2");
        Resultat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Resultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 40));

        terra.setText("La terra");
        getContentPane().add(terra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 30));
        getContentPane().add(nomPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 100, 30));

        fotoPlanetaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(fotoPlanetaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 100));

        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 50, 50));

        jLabel2.setText(" Calcular");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 50, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Fisic fisico = new Fisic();
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String planeta = jList1.getSelectedValue();
         canviarPlaneta(planeta);
        // canviarFoto(planeta);
         try{
             canviarTemps(fisico.getTemps(planeta));
         }catch (SQLException e){
             
         }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    public void canviarTemps(double temps){
        Resultat.setText(Double.toString(temps));
    }
    
    public void canviarPlaneta(String planeta){
        nomPlaneta.setText(planeta);
    }
    
    //Cambiar rutas de las fotos
    /*public void canviarFoto(String planeta){
        String url=null;
        switch (planeta){
            case "Mart":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\marte.jpg";
            break;
            case "Venus":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\Venus.jpg";
            break;
            case "Ura":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\Urano.jpg";
            break;
            case "Saturn":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\Saturno.jpg";
            break;
            case "Mercuri":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\Mercurio.jpg";
            break;
            case "Neptu":
                url="C:\\Users\\xavia\\Documents\\NetBeansProjects\\mavenproject3\\src\\main\\java\\com\\mycompany\\mavenproject3\\Imagenes\\Neptuno.jpg";
            break;
        }
        fotoPlanetaDestino.setIcon(new javax.swing.ImageIcon(url));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Resultat;
    private javax.swing.JLabel fotoPlanetaDestino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomPlaneta;
    private javax.swing.JTextField terra;
    // End of variables declaration//GEN-END:variables
}
